-- =============================================
-- Project      : Zara Sales Analysis
-- File         : 02_basic_insights.sql
-- Author       : Jhalak saxena
-- Description  : Answers core business questions related to product position, top-sellers, gender-based sales, product types, and average price.
-- Database     : SQL Server
-- Source Table : latest_price_table
-- Last Updated : 2025-07-09
-- Query Focus  : Sales by position, gender, product type
-- =============================================

--What is the total revenue generated by each product?
select 
[product id],
product_name,
total_revenue
from latest_price_table
order by Total_Revenue desc ;

-- Which product positions generate the highest sales volume?
select 
[Product Position],
sum ([Sales Volume]) sales_volume
from latest_price_table
group by [Product Position];
-- products on Aisle generate highest sales volume.

 --What are the 10 top-selling products overall?
select top 10 
Product_Name ,
[Sales Volume]
from latest_price_table
order by [Sales Volume] desc;

-- What is the impact of product position (e.g., endcap, aisle) on average sales volume?
WITH product_pos_sales AS (
  SELECT 
    [Product Id],
    product_name,
    [Product Position],
    AVG([Sales Volume]) AS avg_sales_volume
  FROM zara_sales_backup
  GROUP BY [Product Id], product_name, [Product Position]
)

SELECT 
  product_name,
  [Product Position],
  avg_sales_volume,
  RANK() OVER (PARTITION BY product_name ORDER BY avg_sales_volume DESC) AS rank_within_product
FROM product_pos_sales
ORDER BY product_name, rank_within_product;

--Average sales volume variation by gender?
select 
Gender,
avg([Sales Volume]) avg_sales_volume
from latest_price_table
group by Gender 
order by avg([Sales Volume])  desc ;

 --What is the average price of products by type?
select 
type ,
round(avg(price),2) avg_price
from latest_price_table
group by type 
order by round(avg(price),2) desc;

--Which product types sell the most units?
select 
type,
sum([Sales Volume])  as total_sales_volume
from latest_price_table
group by type
order by sum([Sales Volume]) desc;

--Are seasonal products performing better than non-seasonal ones?
select 
seasonal,
avg([sales volume]) as sales_volume_avg
from latest_price_table
group by Seasonal 
order by avg([sales volume]) desc;

